const Data = {
  status: "success",
  items: [
    {
      id: 1,
      title: "Banano x 1000g ",
      price: 1200,
      image: require("./images/uno_Banano.png"),
      category: "Fruta",
      img1: "",
      img2: "",
      cantidad: 1,
    },
    {
      id: 2,
      title: "Durazno x 1000g",
      price: 3200,
      image: require("./images/uno_Durazno.png"),
      category: "Fruta",
      img1: "",
      img2: "",
      cantidad: 1,
    },
    {
      id: 3,
      title: "Fresa x 1000g",
      price: 2400,
      image: require("./images/uno_Fresa.png"),
      category: "Fruta",
      img1: "",
      img2: "",
      cantidad: 1,
    },
    {
      id: 4,
      title: "Guanabana x 1000g",
      price: 3200,
      image: require("./images/uno_Guanabana.png"),
      category: "Fruta",
      img1: "",
      img2: "",
      cantidad: 1,
    },
    {
      id: 5,
      title: "Guayaba x 1000g",
      price: 1200,
      image: require("./images/uno_Guayaba.png"),
      category: "Fruta",
      img1: "",
      img2: "",
      cantidad: 1,
    },
    {
      id: 6,
      title: "Limon x 1000g",
      price: 1400,
      image: require("./images/uno_Limon.png"),
      category: "Fruta",
      img1: "",
      img2: "",
      cantidad: 1,
    },
    {
      id: 7,
      title: "Lulo 1000g",
      price: 1800,
      image: require("./images/uno_Lulo.png"),
      category: "Fruta",
      img1: "",
      img2: "",
      cantidad: 1,
    },
    {
      id: 8,
      title: "Mandarina x 1000g",
      price: 2000,
      image: require("./images/uno_Mandarina.png"),
      category: "Fruta",
      img1: "",
      img2: "",
      cantidad: 1,
    },
    {
      id: 9,
      title: "Mango x 1000g",
      price: 1600,
      image: require("./images/uno_Mango.png"),
      category: "Fruta",
      img1: "",
      img2: "",
      cantidad: 1,
    },
    {
      id: 10,
      title: "Manzana Roja x 1000g",
      price: 1900,
      image: require("./images/uno_ManzanaR.png"),
      category: "Fruta",
      img1: "",
      img2: "",
      cantidad: 1,
    },
    {
      id: 11,
      title: "Manzana Verde x 1000g",
      price: 2100,
      image: require("./images/uno_ManzanaV.png"),
      category: "Fruta",
      img1: "",
      img2: "",
      cantidad: 1,
    },
    {
      id: 12,
      title: "Melon x 1000g",
      price: 2100,
      image: require("./images/uno_Melon.png"),
      category: "Fruta",
      img1: "",
      img2: "",
      cantidad: 1,
    },
    {
      id: 13,
      title: "Mora x 1000g",
      price: 1100,
      image: require("./images/uno_Mora.png"),
      category: "Fruta",
      img1: "",
      img2: "",
      cantidad: 1,
    },
    {
      id: 14,
      title: "Naranja x 1000g",
      price: 1600,
      image: require("./images/uno_Naranja.png"),
      category: "Fruta",
      img1: "",
      img2: "",
      cantidad: 1,
    },
    {
      id: 15,
      title: "Papaya x 1000g",
      price: 1600,
      image: require("./images/uno_Papaya.png"),
      category: "Fruta",
      img1: "",
      img2: "",
      cantidad: 1,
    },
    {
      id: 16,
      title: "Pera x 1000g",
      price: 2100,
      image: require("./images/uno_Pera.png"),
      category: "Fruta",
      img1: "",
      img2: "",
      cantidad: 1,
    },
    {
      id: 17,
      title: "Piña x 1000g",
      price: 1600,
      image: require("./images/uno_Pina.png"),
      category: "Fruta",
      img1: "",
      img2: "",
      cantidad: 1,
    },
    {
      id: 18,
      title: "Kiwi x 1000g",
      price: 2150,
      image: require("./images/uno_Quiwi.png"),
      category: "Fruta",
      img1: "",
      img2: "",
      cantidad: 1,
    },
    {
      id: 19,
      title: "Uva x 1000g",
      price: 1950,
      image: require("./images/uno_Uva.png"),
      category: "Fruta",
      img1: "",
      img2: "",
      cantidad: 1,
    },
    {
      id: 20,
      title: "Acelga x 1000g",
      price: 1100,
      image: require("./images/dos_Acelga.png"),
      category: "Verdura",
      img1: "",
      img2: "",
      cantidad: 1,
    },
    {
      id: 21,
      title: "Aguacate x 1000g",
      price: 2800,
      image: require("./images/dos_Aguacate.png"),
      category: "Verdura",
      img1: "",
      img2: "",
      cantidad: 1,
    },
    {
      id: 22,
      title: "Apio x 1000g",
      price: 1400,
      image: require("./images/dos_Apio.png"),
      category: "Verdura",
      img1: "",
      img2: "",
      cantidad: 1,
    },
    {
      id: 23,
      title: "Berenjena x 1000g",
      price: 2250,
      image: require("./images/dos_Berenjena.png"),
      category: "Verdura",
      img1: "",
      img2: "",
      cantidad: 1,
    },
    {
      id: 24,
      title: "Arroz x 1000g",
      price: 2100,
      image: require("./images/tres_Arroz.png"),
      category: "Legumbres",
      img1: "",
      img2: "",
      cantidad: 1,
    },
    {
      id: 25,
      title: "Arveja x 1000g",
      price: 4200,
      image: require("./images/tres_Arveja.png"),
      category: "Legumbres",
      img1: "",
      img2: "",
      cantidad: 1,
    },
    {
      id: 26,
      title: "Avena x 1000g",
      price: 2100,
      image: require("./images/tres_Avena.png"),
      category: "Legumbres",
      img1: "",
      img2: "",
      cantidad: 1,
    },
    {
      id: 27,
      title: "Café x 1000g",
      price: 2450,
      image: require("./images/tres_Cafe.png"),
      category: "Legumbres",
      img1: "",
      img2: "",
      cantidad: 1,
    },
    {
      id: 28,
      title: "Ajo x 1000g",
      price: 3700,
      image: require("./images/cuatro_Ajo.png"),
      category: "Tuberculos",
      img1: "",
      img2: "",
      cantidad: 1,
    },
    {
      id: 29,
      title: "Arracacha x 1000g",
      price: 2100,
      image: require("./images/cuatro_Arracacha.png"),
      category: "Tuberculos",
      img1: "",
      img2: "",
      cantidad: 1,
    },
    {
      id: 30,
      title: "Jengibre x 1000g",
      price: 4200,
      image: require("./images/cuatro_Jengibre.png"),
      category: "Tuberculos",
      img1: "",
      img2: "",
      cantidad: 1,
    },
    {
      id: 31,
      title: "Papa Criolla x 1000g",
      price: 2250,
      image: require("./images/cuatro_Papa_criolla.png"),
      category: "Tuberculos",
      img1: "",
      img2: "",
      cantidad: 1,
    },
    {
      id: 32,
      title: "Leche x 1000ml",
      price: 2700,
      image: require("./images/cinco_Leche.png"),
      category: "Lacteos",
      img1: "",
      img2: "",
      cantidad: 1,
    },
    {
      id: 33,
      title: "Mantequilla x 1000g",
      price: 7200,
      image: require("./images/cinco_Mantequilla.png"),
      category: "Lacteos",
      img1: "",
      img2: "",
      cantidad: 1,
    },
    {
      id: 34,
      title: "Quajada x 1000g",
      price: 6800,
      image: require("./images/cinco_Quajada.png"),
      category: "Lacteos",
      img1: "",
      img2: "",
      cantidad: 1,
    },
    {
      id: 35,
      title: "Queso Campesino x 1000g",
      price: 7500,
      image: require("./images/cinco_Queso_Campesino.png"),
      category: "Lacteos",
      img1: "",
      img2: "",
      cantidad: 1,
    },
    {
      id: 36,
      title: "Huevos A x 12un",
      price: 3600,
      image: require("./images/seis_HuevosA_X12.png"),
      category: "Huevos",
      img1: "",
      img2: "",
      cantidad: 1,
    },
    {
      id: 37,
      title: "Huevos A x 30un",
      price: 7800,
      image: require("./images/seis_HuevosA_X30.png"),
      category: "Huevos",
      img1: "",
      img2: "",
      cantidad: 1,
    },
    {
      id: 38,
      title: "Huevos AA x 12un",
      price: 4300,
      image: require("./images/seis_HuevosAA_X12.png"),
      category: "Huevos",
      img1: "",
      img2: "",
      cantidad: 1,
    },
    {
      id: 39,
      title: "Huevos AA x 30un",
      price: 9000,
      image: require("./images/seis_HuevosAA_X30.png"),
      category: "Huevos",
      img1: "",
      img2: "",
      cantidad: 1,
    },
    {
      id: 40,
      title: "Alas Pollo x 1000g",
      price: 5000,
      image: require("./images/siete_Alas_Pollo.png"),
      category: "Carnes",
      img1: "",
      img2: "",
      cantidad: 1,
    },
    {
      id: 41,
      title: "Bagre x 1000g",
      price: 10500,
      image: require("./images/siete_Bagre.png"),
      category: "Carnes",
      img1: "",
      img2: "",
      cantidad: 1,
    },
    {
      id: 42,
      title: "Cerdo x 1000g",
      price: 11500,
      image: require("./images/siete_Carne_Cerdo.png"),
      category: "Carnes",
      img1: "",
      img2: "",
      cantidad: 1,
    },
    {
      id: 43,
      title: "Carne Res x 1000g",
      price: 12000,
      image: require("./images/siete_Carne_Res.png"),
      category: "Carnes",
      img1: "",
      img2: "",
      cantidad: 1,
    },
    {
      id: 44,
      title: "Aceite Oliva x 1000ml",
      price: 9600,
      image: require("./images/ocho_Aceite_Oliva.png"),
      category: "Otros",
      img1: "",
      img2: "",
      cantidad: 1,
    },
    {
      id: 45,
      title: "Chocolate x 1000g",
      price: 12000,
      image: require("./images/ocho_Chocolate.png"),
      category: "Otros",
      img1: "",
      img2: "",
      cantidad: 1,
    },
    {
      id: 46,
      title: "Azucar x 1000g",
      price: 1450,
      image: require("./images/ocho_Azucar.png"),
      category: "Otros",
      img1: "",
      img2: "",
      cantidad: 1,
    },
    {
      id: 47,
      title: "Miel x 1000ml",
      price: 12500,
      image: require("./images/ocho_Miel.png"),
      category: "Otros",
      img1: "",
      img2: "",
      cantidad: 1,
    },
  ],
};

export default Data;
